name: Deploy to EC2 and Run Docker Compose

on:
  push:
    branches:
      - development  # Adjust this to the branch you want to trigger on

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: development  # Specify the branch to clone

      - name: Check for changes in npm packages
        id: npm_changed
        run: |
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^package.json$|^package-lock.json$|^node_modules/')
          if grep -q '"dependencies":' package.json; then
            dependencies_changed=1
          else
            dependencies_changed=0
          fi
          if [[ -n "$changed" || $dependencies_changed == 1 ]]; then
            echo "NPM packages or dependencies changed"
            echo "::set-output name=npm_changed::true"
          else
            echo "No changes in NPM packages or dependencies"
            echo "::set-output name=npm_changed::false"
          fi

      - name: Stop and remove all containers if package.json changed
        if: steps.npm_changed.outputs.npm_changed == 'true'
        run: |
          sudo docker stop $(sudo docker ps -a -q) || true
          sudo docker rm $(sudo docker ps -a -q) || true
          sudo docker rmi $(sudo docker images -q) || true
          sudo docker volume prune -f || true

      - name: Install Docker if not installed
        if: steps.npm_changed.outputs.npm_changed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose if not installed
        if: steps.npm_changed.outputs.npm_changed == 'true'
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

      - name: Build and start containers
        run: |
          cd /home/ubuntu/actions-runner/_work/githubAction-CICD/githubAction-CICD
          sudo docker-compose down --remove-orphans
          sudo docker compose up -d


